interface MyMessage {
  _data: {
    id: {
      fromMe: boolean;
      remote: string;
      id: string;
      _serialized: string;
    };
    viewed: boolean;
    body: string;
    type: string;
    t: number;
    notifyName: string;
    from: string;
    to: string;
    ack: number;
    invis: boolean;
    isNewMsg: boolean;
    star: boolean;
    kicNotified: boolean;
    recvFresh: boolean;
    isFromTemplate: boolean;
    thumbnail: string;
    pollInvalidated: boolean;
    isSentCagPollCreation: boolean;
    latestEditMsgKey: string | null;
    latestEditSenderTimestampMs: number | null;
    mentionedJidList: string[];
    groupMentions: string[];
    isEventCanceled: boolean;
    eventInvalidated: boolean;
    isVcardOverMmsDocument: boolean;
    labels: string[];
    hasReaction: boolean;
    ephemeralDuration: number;
    ephemeralSettingTimestamp: number;
    disappearingModeInitiator: string;
    disappearingModeTrigger: string;
    productHeaderImageRejected: boolean;
    lastPlaybackProgress: number;
    isDynamicReplyButtonsMsg: boolean;
    isCarouselCard: boolean;
    parentMsgId: string | null;
    isMdHistoryMsg: boolean;
    stickerSentTs: number;
    isAvatar: boolean;
    lastUpdateFromServerTs: number;
    invokedBotWid: string | null;
    bizBotType: string | null;
    botResponseTargetId: string | null;
    botPluginType: string | null;
    botPluginReferenceIndex: number | null;
    botPluginSearchProvider: string | null;
    botPluginSearchUrl: string | null;
    botPluginSearchQuery: string | null;
    botPluginMaybeParent: boolean;
    botReelPluginThumbnailCdnUrl: string | null;
    botMsgBodyType: string | null;
    requiresDirectConnection: boolean | null;
    bizContentPlaceholderType: string | null;
    hostedBizEncStateMismatch: boolean;
    senderOrRecipientAccountTypeHosted: boolean;
    placeholderCreatedWhenAccountIsHosted: boolean;
    links: string[];
  };
  mediaKey: string | undefined;
  id: {
    fromMe: boolean;
    remote: string;
    id: string;
    _serialized: string;
  };
  ack: number;
  hasMedia: boolean;
  body: string;
  type: string;
  timestamp: number;
  from: string;
  to: string;
  author: string | undefined;
  deviceType: string;
  isForwarded: boolean | undefined;
  forwardingScore: number;
  isStatus: boolean;
  isStarred: boolean;
  broadcast: boolean | undefined;
  fromMe: boolean;
  hasQuotedMsg: boolean;
  hasReaction: boolean;
  duration: number | undefined;
  location: string | undefined;
  vCards: string[];
  inviteV4: string | undefined;
  mentionedIds: string[];
  groupMentions: string[];
  orderId: string | undefined;
  token: string | undefined;
  isGif: boolean;
  isEphemeral: boolean | undefined;
  links: string[];
}

export default MyMessage;